spring:
  application:
    name: minprogram
    version: 1.0.0

  datasource:
    url: jdbc:mysql://172.17.0.9:3306/travel_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    #sh-cynosdbmysql-grp-cr0kwxee.sql.tencentcdb.com:21733 --外网地址
    username: chenyapeng
    password: Admin01!
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 3000ms
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false

server:
  port: 8080
  servlet:
    context-path: minprogram
app:
  jwt:
    secret: "replace-with-your-very-strong-secret-key-min-32-bytes"
    expire-seconds: 604800
  wx:
    app-id: "your-wechat-appid"
    app-secret: "your-wechat-appsecret"

