CREATE TABLE IF NOT EXISTS image (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    image_url VARCHAR(512) NOT NULL,
    target_type TINYINT DEFAULT NULL COMMENT '关联类型 1头像 2文章封面 3文章内容图 4行程图片',
    target_id BIGINT DEFAULT NULL COMMENT '关联目标ID',
    status TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_image_target (target_type, target_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;